# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SubscribeReq.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SubscribeReq.proto',
  package='example',
  serialized_pb='\n\x12SubscribeReq.proto\x12\x07\x65xample\"X\n\x0cSubscribeReq\x12\x10\n\x08subReqID\x18\x01 \x02(\x05\x12\x10\n\x08userName\x18\x02 \x02(\t\x12\x13\n\x0bproductName\x18\x03 \x02(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x03(\t')




_SUBSCRIBEREQ = _descriptor.Descriptor(
  name='SubscribeReq',
  full_name='example.SubscribeReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='subReqID', full_name='example.SubscribeReq.subReqID', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='userName', full_name='example.SubscribeReq.userName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='productName', full_name='example.SubscribeReq.productName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='example.SubscribeReq.address', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=31,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['SubscribeReq'] = _SUBSCRIBEREQ

class SubscribeReq(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SUBSCRIBEREQ

  # @@protoc_insertion_point(class_scope:example.SubscribeReq)


# @@protoc_insertion_point(module_scope)
